# Generated by Django 3.1.1 on 2020-09-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_update_app', '0002_auto_20200912_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='passworld',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='classname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
