# Generated by Django 3.1.1 on 2020-09-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_update_app', '0004_auto_20200912_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
