# Generated by Django 3.1.1 on 2020-09-14 08:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('class_update_app', '0007_auto_20200914_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassInfoModel',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='classname',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), null=True, size=100),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='content',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), null=True, size=100),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='url',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), null=True, size=100),
        ),
    ]
