# Generated by Django 3.1.1 on 2020-09-15 06:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('class_update_app', '0008_auto_20200914_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='diffclassname',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), null=True, size=100),
        ),
    ]
