# Generated by Django 3.1.1 on 2020-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_update_app', '0011_classmodel_sumcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='sumcontent',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='lenclass',
            field=models.IntegerField(null=True),
        ),
    ]
